In [ ]:
import duckdb
import pandas as pd

In [10]:
from sys import displayhook


sql_query = '''
show tables
'''

with duckdb.connect('data/nyc_parking_violations.db') as con:
    displayhook(con.sql(sql_query).df())

                              name
0   bronze_parking_violation_codes
1        bronze_parking_violations
2                      first_model
3              gold_ticket_metrics
4            gold_vehicles_metrics
5          parking_violation_codes
6          parking_violations_2023
7                        ref_model
8   silver_parking_violation_codes
9        silver_parking_violations
10        silver_violation_tickets
11       silver_violation_vehicles

In [5]:
from sys import displayhook


sql_query = '''
SELECT * FROM "bronze_parking_violations" LIMIT 5
'''

with duckdb.connect('data/nyc_parking_violations.db') as con:
    displayhook(con.sql(sql_query).df())

,summons_number,registration_state,plate_type,issue_date,violation_code,vehicle_body_type,vehicle_make,issuing_agency,vehicle_expiration_date,violation_location,violation_precinct,issuer_precinct,issuer_code,issuer_command,issuer_squad,violation_time,violation_county,violation_legal_code,vehicle_color,vehicle_year
0,9010912681,CA,PAS,2022-10-11,17,SUBN,FORD,T,20220788,50,50,50,365910,T201,D,0825A,BX,<NA>,BLACK,0
1,4858762841,NY,PAS,2023-08-21,36,4DSD,HONDA,V,0,<NA>,0,0,0,None,None,1036A,BK,True,GY,2003
2,4854645684,FL,PAS,2023-07-26,36,UT,BMW,V,0,<NA>,0,0,0,None,None,0126P,QN,True,WHI,2022
3,9044582707,NY,PAS,2023-04-10,21,SUBN,SUBAR,T,20231217,79,79,79,370326,T301,H,0924A,K,<NA>,GY,2017
4,9041503330,NY,PAS,2023-03-21,21,4DSD,CHEVR,T,20250320,26,26,26,373097,T103,C,1155A,NY,<NA>,BK,2018